"use client";

import { useState, useEffect } from "react";
import { AdminDashboardHeader, AdminFilterBar } from "@/components/admin/dashboard";
import {
  KeyRound,
  CheckCircle2,
  XCircle,
  Download,
  BookOpen,
  Calendar,
  Loader2,
  User,
  Clock
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { fetchAccessCodes, expireAccessCode } from "@/app/api/access-codes/client";
import { Pagination } from "@/components/ui/pagination";

type AccessCodeStatusTab = "all" | "unused" | "redeemed" | "expired";

const statusConfig = {
  unused: {
    label: "Unused",
    color: "text-[#0E7B33]",
    bg: "bg-[#E7F6EC]",
    border: "border-[#0E7B33]/20",
    icon: CheckCircle2,
  },
  redeemed: {
    label: "Redeemed",
    color: "text-[#1D4ED8]",
    bg: "bg-[#DBEAFE]",
    border: "border-[#1D4ED8]/20",
    icon: User,
  },
  expired: {
    label: "Expired",
    color: "text-[#DC2626]",
    bg: "bg-[#FEE2E2]",
    border: "border-[#DC2626]/20",
    icon: XCircle,
  },
};

export default function AdminAccessCodesPage() {
  const [activeTab, setActiveTab] = useState<AccessCodeStatusTab>("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [page, setPage] = useState(1);
  const queryClient = useQueryClient();

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(searchQuery);
    }, 300);
    return () => clearTimeout(timer);
  }, [searchQuery]);

  const { data: queryData, isLoading } = useQuery({
    queryKey: ["admin-access-codes", page, debouncedSearch, activeTab],
    queryFn: () => fetchAccessCodes({ page, limit: 15, search: debouncedSearch || undefined, status: activeTab }),
  });

  const expireMutation = useMutation({
    mutationFn: (id: string) => expireAccessCode(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["admin-access-codes"] });
    },
  });

  const codes = queryData?.data || [];
  const totalCount = queryData?.total || 0;
  const totalPages = queryData ? Math.ceil(queryData.total / queryData.limit) : 1;

  return (
    <div className="min-h-screen bg-[#F7F9FC]">
      <AdminDashboardHeader />
      <div className="px-4 sm:px-6 lg:px-8 py-6 sm:py-8 space-y-6 max-w-7xl mx-auto">
        {/* Unboxed Modern Page Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-[#0A1B39]">
              Access Codes
            </h1>
            <p className="text-xs sm:text-sm text-[#676E85] mt-1 font-normal">
              Monitor course access codes generated by agent proxy purchases.
            </p>
          </div>
          <Button
            variant="outline"
            className="border-neutral-200 text-[#0A1B39] rounded-md h-9 px-4 font-semibold text-xs w-fit hover:bg-neutral-50 shadow-2xs"
          >
            <Download className="h-4 w-4 mr-1.5" />
            Export List
          </Button>
        </div>

        {/* Stats Row */}
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 sm:gap-5">
          {[
            {
              label: "Total Codes",
              value: (queryData?.stats?.totalCodes ?? 0).toLocaleString(),
              icon: KeyRound,
              color: "text-[#17A546]",
              bg: "bg-[#17A546]/10",
              period: "All generated codes",
            },
            {
              label: "Unused Codes",
              value: (queryData?.stats?.unusedCodes ?? 0).toLocaleString(),
              icon: CheckCircle2,
              color: "text-[#0E7B33]",
              bg: "bg-[#0E7B33]/10",
              period: "Ready for redemption",
            },
            {
              label: "Redeemed Codes",
              value: (queryData?.stats?.redeemedCodes ?? 0).toLocaleString(),
              icon: User,
              color: "text-[#1D4ED8]",
              bg: "bg-[#1D4ED8]/10",
              period: "Claimed by students",
            },
            {
              label: "Expired Codes",
              value: (queryData?.stats?.expiredCodes ?? 0).toLocaleString(),
              icon: XCircle,
              color: "text-[#DC2626]",
              bg: "bg-[#DC2626]/10",
              period: "Inactive / revoked",
            },
          ].map((stat) => (
            <div
              key={stat.label}
              className="bg-white rounded-md p-5 border border-neutral-200/80 shadow-xs hover:border-[#17A546]/30 transition-all duration-200 group"
            >
              <div className="flex items-start justify-between mb-3">
                <div className={`${stat.bg} rounded-md p-2.5 border border-neutral-100 group-hover:scale-105 transition-transform duration-200`}>
                  <stat.icon className={`h-5 w-5 ${stat.color}`} />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-[#0A1B39]">
                {stat.value}
              </p>
              <p className="text-xs text-[#676E85] mt-1 font-medium">{stat.label}</p>
              <p className="text-[11px] text-[#98A2B3] mt-0.5">{stat.period}</p>
            </div>
          ))}
        </div>

        {/* Unified Filter & Search Bar */}
        <AdminFilterBar
          tabs={[
            { key: "all", label: "All Codes" },
            { key: "unused", label: "Unused" },
            { key: "redeemed", label: "Redeemed" },
            { key: "expired", label: "Expired" },
          ]}
          activeTab={activeTab}
          onTabChange={(tab) => {
            setActiveTab(tab as AccessCodeStatusTab);
            setPage(1);
          }}
          searchQuery={searchQuery}
          onSearchChange={(val) => {
            setSearchQuery(val);
            setPage(1);
          }}
          searchPlaceholder="Search code, course, or student..."
        />

        {/* Table Container */}
        <div className="bg-white rounded-md border border-neutral-200/80 shadow-2xs overflow-hidden">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-20 text-[#676E85]">
              <Loader2 className="w-8 h-8 animate-spin text-[#17A546] mb-2" />
              <p className="text-xs font-semibold">Loading access codes...</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-neutral-200/80 bg-neutral-50/60">
                    <th className="text-left text-[10px] uppercase tracking-wider font-semibold text-[#676E85] px-5 py-3">
                      Access Code
                    </th>
                    <th className="text-left text-[10px] uppercase tracking-wider font-semibold text-[#676E85] px-5 py-3 hidden sm:table-cell">
                      Course & Agent
                    </th>
                    <th className="text-left text-[10px] uppercase tracking-wider font-semibold text-[#676E85] px-5 py-3 hidden md:table-cell">
                      Dates
                    </th>
                    <th className="text-left text-[10px] uppercase tracking-wider font-semibold text-[#676E85] px-5 py-3">
                      Status
                    </th>
                    <th className="text-right text-[10px] uppercase tracking-wider font-semibold text-[#676E85] px-5 py-3">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-100">
                  {codes.map((item: any) => {
                    const status = statusConfig[item.status as keyof typeof statusConfig];
                    return (
                      <tr
                        key={item.id}
                        className="hover:bg-neutral-50/60 transition-colors group"
                      >
                        <td className="px-5 py-3.5">
                          <div className="min-w-0">
                            <p className="text-xs font-mono font-bold text-[#0A1B39] bg-neutral-100 px-2 py-1 rounded-md border border-neutral-200 w-fit">
                              {item.code}
                            </p>
                          </div>
                        </td>
                        <td className="px-5 py-3.5 hidden sm:table-cell">
                          <div className="flex flex-col gap-0.5">
                            <span className="text-xs font-semibold text-[#0A1B39] flex items-center gap-1.5">
                              <BookOpen className="w-3 h-3 text-[#17A546]" /> {item.course?.title}
                            </span>
                            <span className="text-[11px] text-[#676E85]">
                              Agent: {item.affiliate?.referralCode}
                            </span>
                          </div>
                        </td>
                        <td className="px-5 py-3.5 hidden md:table-cell">
                          <div className="flex flex-col gap-1">
                            <span className="text-[11px] text-[#676E85] flex items-center gap-1.5">
                              <Calendar className="w-3 h-3 text-[#98A2B3]" /> 
                              Gen: {new Date(item.createdAt).toLocaleDateString()}
                            </span>
                            {item.redeemedAt && (
                              <span className="text-[11px] text-[#676E85] flex items-center gap-1.5">
                                <CheckCircle2 className="w-3 h-3 text-[#17A546]" />
                                Used: {new Date(item.redeemedAt).toLocaleDateString()}
                              </span>
                            )}
                          </div>
                        </td>
                        <td className="px-5 py-3.5">
                          <div className="flex flex-col gap-1 items-start">
                            <span
                              className={cn(
                                "inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-md border",
                                status.color,
                                status.bg,
                                status.border
                              )}
                            >
                              <status.icon className="w-3 h-3" />
                              {status.label}
                            </span>
                            {item.status === "redeemed" && item.redeemedByUser && (
                              <span className="text-[10px] text-[#676E85] max-w-[120px] truncate">
                                by {item.redeemedByUser.name}
                              </span>
                            )}
                          </div>
                        </td>
                        <td className="px-5 py-3.5">
                          <div className="flex items-center justify-end gap-1.5">
                            {item.status === "unused" && (
                              <button
                                onClick={() => expireMutation.mutate(item.id)}
                                disabled={expireMutation.isPending}
                                className="text-xs font-medium px-2.5 py-1 rounded-md transition-colors text-red-600 hover:bg-red-50 disabled:opacity-50"
                              >
                                Expire Manually
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}

          {!isLoading && codes.length === 0 && (
            <div className="text-center py-16">
              <KeyRound className="h-10 w-10 text-[#98A2B3] mx-auto mb-3" />
              <p className="text-sm font-semibold text-[#0A1B39]">
                No access codes found
              </p>
              <p className="text-xs text-[#676E85] mt-1">
                Try adjusting your search query or status filter.
              </p>
            </div>
          )}

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="p-4 border-t border-neutral-100 flex items-center justify-center">
              <Pagination currentPage={page} totalPages={totalPages} onPageChange={setPage} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
